export const FETCH_PRODUCTS_REQUEST='FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_SUCCESS='FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL='FETCH_PRODUCTS_FAIL'

export const ADD_TO_CART = 'ADD_TO_CART'
export const ADJUST_QTY = 'ADJUST_QTY'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
